export const incident_types =
[
  { id: 1, label: 'Medical Emergency', sequence: 1 },
  { id: 2, label: 'Motor Accident', sequence: 1 },
  { id: 3, label: 'Viber Report Message', sequence: 1 },
  { id: 4, label: 'Injury Incident', sequence: 1 },
  { id: 5, label: 'Vehicle Accident', sequence: 1 },
  { id: 6, label: 'Fire Emergency', sequence: 1 },
  { id: 7, label: 'Road Traffic Accidents', sequence: 1 },
  { id: 8, label: 'Physical Assaults', sequence: 1 },
  { id: 9, label: 'Fatal Accidents', sequence: 1 },
  { id: 10, label: 'Floods', sequence: 1 },
  { id: 11, label: 'Tropical Storms', sequence: 1 },
  { id: 12, label: 'Hurricanes Storms', sequence: 1 },
  { id: 13, label: 'Earthquakes', sequence: 1 },
  { id: 14, label: 'Wildfires', sequence: 1 },
  { id: 15, label: 'Bomb Threat', sequence: 1 },
  { id: 16, label: 'Hostage Situation', sequence: 1 },
  { id: 17, label: 'Severe Weather', sequence: 1 },
  { id: 18, label: 'Civil Disturbances', sequence: 1 },
  { id: 19, label: 'Car Accident', sequence: 1 },
  { id: 20, label: 'Hurricane', sequence: 1 },
  { id: 21, label: 'Landslide', sequence: 1 },
  { id: 22, label: 'Power Outage', sequence: 1 },
  { id: 23, label: 'Thunderstorm', sequence: 1 },
  { id: 24, label: 'Water Safety', sequence: 1 },
  { id: 25, label: 'Poisoning', sequence: 1 },
  { id: 26, label: 'Food Poison', sequence: 1 },
  { id: 27, label: 'Heart Attack', sequence: 1 },
  { id: 28, label: 'Pool Drown', sequence: 1 },
  { id: 29, label: 'Swimming Pool Accident', sequence: 1 },
  { id: 30, label: 'Suspicious Activity', sequence: 1 },
  { id: 31, label: 'Theft', sequence: 1 },
  { id: 32, label: 'Abuse', sequence: 1 },
  { id: 33, label: 'Harassment', sequence: 1 },
  { id: 34, label: 'Car Crash', sequence: 1 },
  { id: 35, label: 'Motor Crash', sequence: 1 },
  { id: 36, label: 'Fire Burn', sequence: 1 },
  { id: 37, label: 'Skin Burn', sequence: 1 },
  { id: 38, label: 'Motor Theft', sequence: 1 },
  { id: 39, label: 'Car Theft', sequence: 1 },
  { id: 40, label: 'Security Incident', sequence: 1 },
  { id: 41, label: 'Property Damage', sequence: 1 },
  { id: 42, label: 'Death/Serious Incident', sequence: 1 },
  { id: 43, label: 'Drowning', sequence: 1 },
  { id: 44, label: 'High Blood', sequence: 1 },
  { id: 45, label: 'River Overflow', sequence: 1 },
  { id: 46, label: 'River Drowning', sequence: 1 },
  { id: 47, label: 'Road Flood', sequence: 1 },
  { id: 48, label: 'Road Landslide', sequence: 1 },
  { id: 49, label: 'Cardiac Arrest', sequence: 1 },
  { id: 50, label: 'Covid Report', sequence: 1 },
  { id: 51, label: 'Road Closed', sequence: 1 },
  { id: 52, label: 'Truck Accident', sequence: 1 },
  { id: 53, label: 'Motorcycle Accident', sequence: 1 },
  { id: 54, label: 'Bike Accident', sequence: 1 },
  { id: 55, label: 'Private Property Tresspassing', sequence: 1 },
  { id: 56, label: 'Tresspassing', sequence: 1 },
  { id: 57, label: 'Noise Complaint', sequence: 1 },
  { id: 58, label: 'Car Fire Accident', sequence: 1 },
  { id: 59, label: 'Overspeeding', sequence: 1 },
  { id: 60, label: 'Traffic Accident', sequence: 1 },
  { id: 61, label: 'Death Threat', sequence: 1 },
  { id: 62, label: 'School Accident', sequence: 1 },
  { id: 63, label: 'School Fire Accident', sequence: 1 },
  { id: 64, label: 'Residential Disturbance', sequence: 1 },
  { id: 65, label: 'Disturbance', sequence: 1 },
  { id: 66, label: 'Chaos', sequence: 1 },
  { id: 67, label: 'Damage Property', sequence: 1 },
  { id: 68, label: 'Bomb Accident', sequence: 1 },
  { id: 69, label: 'Bullying', sequence: 1 },
  { id: 70, label: 'School Bullying', sequence: 1 },
  { id: 71, label: 'Child Abuse', sequence: 1 },
  { id: 72, label: 'Rape', sequence: 1 },
  { id: 73, label: 'Virus Report', sequence: 1 },
  { id: 74, label: 'Medical Assistant Report', sequence: 1 },
  { id: 75, label: 'Inquiry', sequence: 1 },
  { id: 76, label: 'Need Rescue', sequence: 1 },
  { id: 77, label: 'Rescue Assistance', sequence: 1 },
  { id: 78, label: 'Need Ambulance', sequence: 1 },
  { id: 79, label: 'Forest Fire', sequence: 1 },
  { id: 80, label: 'Residential Fire', sequence: 1 },
  { id: 81, label: 'School Fire', sequence: 1 },
  { id: 82, label: 'Lost Person', sequence: 1 },
  { id: 83, label: 'Road Traffic Accident', sequence: 1 },
  { id: 84, label: 'Clinical Negligence', sequence: 1 },
  { id: 85, label: 'Sports Related Injuries', sequence: 1 },
  { id: 86, label: 'Animal Accident', sequence: 1 },
  { id: 87, label: 'Animal Bites', sequence: 1 },
  { id: 88, label: 'Sexual Harassment', sequence: 1 },
  { id: 89, label: 'Assault', sequence: 1 },
  { id: 90, label: 'Hate Crimes', sequence: 1 },
  { id: 91, label: 'Hazing', sequence: 1 },
  { id: 92, label: 'Domestic Violence', sequence: 1 },
  { id: 93, label: 'Discrimination', sequence: 1 },
  { id: 94, label: 'Fraud', sequence: 1 },
  { id: 95, label: 'Concerns', sequence: 1 },
  { id: 96, label: 'Vandalism', sequence: 1 },
  { id: 97, label: 'Unauthorized Access', sequence: 1 },
  { id: 98, label: 'Suicide Risks', sequence: 1 },
  { id: 99, label: 'Weapons', sequence: 1 },
  { id: 100, label: 'Illegal Gambling', sequence: 1 },
  { id: 101, label: 'Exploitation', sequence: 1 },
  { id: 102, label: 'Intruder', sequence: 1 },
  { id: 103, label: 'Collisions', sequence: 1 },
  { id: 104, label: 'Stalking', sequence: 1 },
  { id: 105, label: 'Catcalling', sequence: 1 },
  { id: 106, label: 'Street Harassment', sequence: 1 },
  { id: 107, label: 'Identity Theft', sequence: 1 },
  { id: 108, label: 'Terrorism', sequence: 1 },
  { id: 109, label: 'Wanted Person Report', sequence: 1 },
  { id: 110, label: 'Illegal Firearms', sequence: 1 },
  { id: 111, label: 'Illegal Sabong', sequence: 1 },
  { id: 112, label: 'Illegal Drugs', sequence: 1 },
  { id: 113, label: 'Illegal Weapons', sequence: 1 },
  { id: 114, label: 'Email Report', sequence: 1 },
  { id: 115, label: 'Traffic Light Violator', sequence: 1 },
  { id: 116, label: 'Pedestrian Accident', sequence: 1 },
  { id: 117, label: 'Beating The Red Light', sequence: 1 },
  { id: 118, label: 'Power Plant Accident', sequence: 1 },
  { id: 119, label: 'Road Crash', sequence: 1 },
  { id: 120, label: 'Bus Accident', sequence: 1 },
  { id: 121, label: 'Bus Collision', sequence: 1 },
  { id: 122, label: 'Bridge Accident', sequence: 1 },
  { id: 123, label: 'Illegal Bike Races', sequence: 1 },
  { id: 124, label: 'Freak Accident', sequence: 1 },
  { id: 125, label: 'Illegal Race', sequence: 1 },
  { id: 126, label: 'Highway Accident', sequence: 1 },
  { id: 127, label: 'Plane Accident', sequence: 1 },
  { id: 128, label: 'Shipyard Accident', sequence: 1 },
  { id: 129, label: 'Port Accident', sequence: 1 },
  { id: 130, label: 'Smuggled Vehicle', sequence: 1 },
  { id: 131, label: 'Fatal Accident', sequence: 1 },
  { id: 132, label: 'Ambushed', sequence: 1 },
  { id: 133, label: 'Cargo Truck Accident', sequence: 1 },
  { id: 134, label: 'Shuttle Bus Accident', sequence: 1 },
  { id: 135, label: 'Shooting Accident', sequence: 1 },
  { id: 136, label: 'Trauma', sequence: 1 },
  { id: 137, label: 'OB-Gyne', sequence: 1 },
  { id: 138, label: 'Others', sequence: 1 },
  { id: 139, label: 'Robbery', sequence: 1 },
  { id: 140, label: 'Physical Abuse', sequence: 1 },
  { id: 141, label: 'Trap Elevator', sequence: 1 },
  { id: 142, label: 'Trap Inside the Car', sequence: 1 },
  { id: 143, label: 'Fire', sequence: 1 },
  { id: 144, label: 'Flood', sequence: 1 },
  { id: 145, label: 'Accident', sequence: 1 },
  { id: 146, label: 'Medical', sequence: 1 }
]