export const user_column = [
    {
        label:"Firstname",
        field:"firstname",
        search:1
    },
    {
        label:"Lastname",
        field:"lastname",
        search:1
    },
    {
        label:"Email",
        field:"email",
        search:1
    },
    {
        label:"Role",
        field:"user_roles.label",
        search:1
    },
]