services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - .:/backend:/var/www/html/ims/backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    # volumes:
    #   - .:/app
    #   - /app/frontend/node_modules
    # command: "npm run dev -- --host --port 5173"
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: imsv2
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8083:80
    environment:
      - PMA_ABITRARY=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
