services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - .:/backend:/var/www/html/ims/backend
    depends_on:
      - mysql_db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: imsv2
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
