version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:cached
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: imsv2
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8082:80
    environment:
      - PMA_ABITRARY=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
