export const user_fields = [
    {
        title:"Basic information",
        fields:[
            {
                label:"Firstname",
                name:"firstname",
                type:"text",
                required:1
            },
            {
                label:"Lastname",
                name:"lastname",
                type:"text",
                required:1
            },
            {
                label:"Email",
                name:"email",
                type:"email",
                required:1
            },
            {
                label:"Role",
                name:"user_roles",
                type:"dropdown",
                required:1,
                option:"set",
                target:"roles"
            },
            {
                label:"Role.",
                name:"roles",
                type:"dropdown",
                required:1,
                option:"get"
            },
            {
                label:"Password",
                name:"password",
                type:"text",
                required:1
            },
        ]
    },
    {
        title:"User Privileges",
        fields:[
            {
                label:"Incident",
                name:"user_privileges.incidents",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Resource",
                name:"user_privileges.resources",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Pre Plan",
                name:"user_privileges.preplans",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Contact",
                name:"user_privileges.contacts",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Agency",
                name:"user_privileges.agencies",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Responder",
                name:"user_privileges.responders",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Call Logs",
                name:"user_privileges.call_logs",
                type:"checkbox",
                default_value:true
            },
            {
                label:"Report",
                name:"user_privileges.reports",
                type:"checkbox",
                default_value:true
            },
        ]
    },
]